//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSeatBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytic
    {
        public int AnalyticsId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> TotalBookings { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<int> TotalTicketsSold { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
