//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSeatBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string Type { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
